apiVersion: v2
name: codetogether-collab
description: CodeTogether Collab

type: application
version: 1.2.9
appVersion: "2026.1.2"

icon: https://www.codetogether.com/wp-content/uploads/2020/02/codetogether-circle-128.png
home: https://www.codetogether.com

maintainers:
- email: info@codetogether.com
  name: CodeTogether Inc.

keywords:
- codetogether
- live
- collaborative
- pair
- programming
